/**
 * 劇情單挑 — scripted one-on-one encounters drawn from the romance: 溫酒斬華雄,
 * 三英戰呂布, 斬顏良誅文醜, 葭萌關挑燈夜戰… Each names a famous opponent, sets
 * the stage, and maps the bout's outcome to concrete effects (gold, renown, the
 * occasional recruit) the host applies through the shared scenario-effect path.
 * The bout itself runs on the interactive 單挑 engine; this is the framing and
 * the spoils. Effects reuse {@link ScenarioEffect} so the store applies them
 * exactly like the 劇情舌戰 scenarios.
 */
import type { EntityId } from '../types';
import type { ScenarioEffect } from './debateScenarios';

export type DuelScenarioKind = 'famous-duel' | 'champion-challenge' | 'grudge';

export interface DuelScenario {
  id: string;
  kind: DuelScenarioKind;
  titleZh: string;
  titleEn: string;
  introZh: string;
  introEn: string;
  /** The famous warrior you must defeat (an existing roster id). */
  opponentId: EntityId;
  /** Effects on a win (whether on points or by a knockout). */
  winEffects: ScenarioEffect[];
  /** Effects on a loss. */
  loseEffects: ScenarioEffect[];
  /** Extra effects when you don't merely win but cut them down (斬殺). */
  slayEffects?: ScenarioEffect[];
}

const gold = (amount: number, zh: string, en: string): ScenarioEffect => ({ kind: 'gold', amount, textZh: zh, textEn: en });
const note = (zh: string, en: string): ScenarioEffect => ({ kind: 'note', textZh: zh, textEn: en });

export const DUEL_SCENARIOS: DuelScenario[] = [
  {
    id: 'slay-hua-xiong',
    kind: 'famous-duel',
    titleZh: '溫酒斬華雄', titleEn: 'Slay Hua Xiong',
    introZh: '華雄連斬聯軍數將,陣前耀武。溫酒尚熱,可敢出陣取其首級?',
    introEn: 'Hua Xiong has cut down champion after champion before the allied host. The wine is still warm — dare you ride out and take his head?',
    opponentId: 'hua-xiong',
    winEffects: [gold(400, '陣前揚名,聯軍犒賞 400 金。', 'Your name rings through the camp — the alliance rewards 400 gold.')],
    loseEffects: [note('不敵華雄,折戟而歸。', 'Bested by Hua Xiong, you withdraw.')],
    slayEffects: [gold(300, '提華雄首級而還 — 酒尚溫熱!威震諸侯。', 'You return with his head — the wine still warm! The lords are awed.')],
  },
  {
    id: 'three-vs-lubu',
    kind: 'famous-duel',
    titleZh: '三英戰呂布', titleEn: 'Battle Lü Bu',
    introZh: '虎牢關前,呂布橫戟立馬,天下無人敢當。遣一員猛將,與這「人中呂布」決一死戰!',
    introEn: 'At Hulao Pass, Lü Bu sits his horse with halberd levelled — none dare face him. Send your fiercest warrior against the peerless one!',
    opponentId: 'lu-bu',
    winEffects: [gold(600, '力撼呂布,威名動天下!', 'You stand against Lü Bu himself — your fame shakes the realm!')],
    loseEffects: [note('呂布勇不可當,你且戰且退。', 'Lü Bu is unstoppable; you give ground.')],
    slayEffects: [gold(800, '陣斬呂布 — 改寫天下大勢的一戰!', 'You cut down Lü Bu — a duel that rewrites history!')],
  },
  {
    id: 'slay-yan-liang',
    kind: 'famous-duel',
    titleZh: '萬軍斬顏良', titleEn: 'Slay Yan Liang',
    introZh: '顏良立馬於萬軍之中,白馬義從環衛。可敢策馬直入,於萬眾之中取其首級?',
    introEn: 'Yan Liang sits amid a host of ten thousand. Dare you charge straight in and take his head before them all?',
    opponentId: 'yan-liang',
    winEffects: [gold(450, '萬軍叢中斬將奪旗,曹公大喜。', 'You cut him down amid the host — your lord is overjoyed.')],
    loseEffects: [note('白馬義從圍攏,你殺出重圍。', 'The white-horse guards close in; you fight your way clear.')],
    slayEffects: [gold(350, '一刀斬顏良於馬下 — 河北軍奪氣!', 'One stroke fells Yan Liang — Hebei\'s host loses heart!')],
  },
  {
    id: 'jiameng-pass',
    kind: 'grudge',
    titleZh: '葭萌關挑燈夜戰', titleEn: 'Torchlit Duel at Jiameng',
    introZh: '馬超與你麾下猛將鬥得難解難分,自午至夜,挑燈再戰。今夜,定要分出高下!',
    introEn: 'Ma Chao and your champion have fought to a standstill from noon into night — torches lit, the duel resumes. Tonight it ends!',
    opponentId: 'ma-chao',
    winEffects: [gold(400, '挑燈夜戰,力壓錦馬超 — 傳為佳話。', 'In the torchlight you master the Splendid Ma Chao — a tale retold for years.')],
    loseEffects: [note('棋逢敵手,難分軒輊,鳴金各歸。', 'Too evenly matched — the gongs sound and both withdraw.')],
  },
  {
    id: 'shenting-taishici',
    kind: 'grudge',
    titleZh: '神亭嶺鬥太史慈', titleEn: 'Duel Taishi Ci at Shenting',
    introZh: '神亭嶺下,太史慈單騎挑戰,要與你部下大將捉對廝殺,以武會友。',
    introEn: 'At Shenting Ridge, Taishi Ci rides out alone to test your champion blade to blade — a duel between worthy foes.',
    opponentId: 'taishi-ci',
    winEffects: [gold(350, '神亭一戰,英雄相惜,威名遠播。', 'A duel of equals at Shenting — your fame spreads far.')],
    loseEffects: [note('太史慈武藝高強,你勉力全身而退。', 'Taishi Ci\'s skill is fierce; your champion withdraws intact.')],
  },
  {
    id: 'tiger-zhang-liao',
    kind: 'champion-challenge',
    titleZh: '逍遙津會張遼', titleEn: 'Face Zhang Liao at Xiaoyao Ford',
    introZh: '逍遙津畔,張遼威震江東。可遣猛將,當面挫其鋒芒?',
    introEn: 'At Xiaoyao Ford, Zhang Liao\'s name alone scatters armies. Send a warrior to blunt his edge?',
    opponentId: 'zhang-liao',
    winEffects: [gold(450, '力克張文遠 — 江東軍心大振!', 'You master Zhang Liao — the southern host takes heart!')],
    loseEffects: [note('張遼勇冠三軍,你部下力戰而還。', 'Zhang Liao\'s valour is unmatched; your champion fights free.')],
    slayEffects: [gold(400, '陣斬張遼 — 止啼之名,今日易主!', 'You cut down Zhang Liao — the terror of the north is undone!')],
  },
  {
    id: 'slay-wen-chou',
    kind: 'famous-duel',
    titleZh: '延津誅文醜', titleEn: 'Slay Wen Chou',
    introZh: '文醜引兵渡河,沿河追擊。延津南阪,可敢回馬一戰,取這河北名將首級?',
    introEn: 'Wen Chou drives his host across the ford in hot pursuit. On the southern slope at Yanjin — dare you wheel your horse and take the Hebei champion\'s head?',
    opponentId: 'wen-chou',
    winEffects: [gold(420, '延津挫文醜,曹營傳為美談。', 'You best Wen Chou at Yanjin — the camp sings of it.')],
    loseEffects: [note('文醜驍勇,你撥馬且退。', 'Wen Chou is fierce; you rein back and withdraw.')],
    slayEffects: [gold(360, '回馬一刀,斬文醜於延津 — 河北再失一上將!', 'A wheeling stroke fells Wen Chou — Hebei loses a second champion!')],
  },
  {
    id: 'tong-pass-xuchu',
    kind: 'grudge',
    titleZh: '潼關許褚裸衣', titleEn: 'Xu Chu Strips for Battle at Tong Pass',
    introZh: '潼關之下,許褚怒目橫刀,竟卸甲裸衣而戰,要與西涼錦馬超捨命相搏。',
    introEn: 'Below Tong Pass, Xu Chu throws off his armour and fights bare-chested — a death-match against the Splendid Ma Chao of Xiliang.',
    opponentId: 'xu-chu',
    winEffects: [gold(430, '裸衣鬥許褚,棋逢敵手,名動關中。', 'A bare-chested duel with Xu Chu — your fame rings through Guanzhong.')],
    loseEffects: [note('虎癡力大,你勒馬暫退。', 'The Tiger-Fool\'s strength is monstrous; you give ground.')],
  },
  {
    id: 'jiange-gan-ning',
    kind: 'champion-challenge',
    titleZh: '百騎劫營鬥甘寧', titleEn: 'Gan Ning of the Hundred Riders',
    introZh: '甘寧引百騎夜劫曹營,鈴聲所至,無不披靡。可遣勇將攔下這錦帆賊?',
    introEn: 'Gan Ning raids the camp by night with a hundred riders — where his bells ring, men scatter. Send a champion to halt the Brocade-Sail Pirate?',
    opponentId: 'gan-ning',
    winEffects: [gold(380, '攔下甘興霸 — 江東劫營之計受挫。', 'You halt Gan Ning — the southern night-raid is blunted.')],
    loseEffects: [note('百騎呼嘯而過,你部下未能攔住。', 'The hundred riders sweep past; your champion cannot hold them.')],
    slayEffects: [gold(320, '陣斬甘寧於營門 — 錦帆鈴聲就此沉寂!', 'You cut down Gan Ning at the gate — the brocade bells fall silent!')],
  },
  {
    id: 'dingjun-xiahou-yuan',
    kind: 'famous-duel',
    titleZh: '定軍山斬夏侯淵', titleEn: 'Slay Xiahou Yuan at Dingjun',
    introZh: '定軍山下,夏侯淵據險而守。老將請纓,要趁其不備,一刀斬於陣前!',
    introEn: 'Below Dingjun Mountain, Xiahou Yuan holds the high ground. An old general begs leave to catch him unready and cut him down at a stroke!',
    opponentId: 'xiahou-yuan',
    winEffects: [gold(460, '定軍一戰,聲威大震 — 漢中門戶洞開。', 'The duel at Dingjun rings out — the gate to Hanzhong swings open.')],
    loseEffects: [note('夏侯淵據險,你且戰且退。', 'Xiahou Yuan holds the heights; you give ground.')],
    slayEffects: [gold(420, '一刀斬夏侯淵於定軍山下 — 曹軍奪氣!', 'One stroke fells Xiahou Yuan beneath Dingjun — Cao\'s host loses heart!')],
  },
  {
    id: 'fancheng-pang-de',
    kind: 'grudge',
    titleZh: '樊城抬櫬戰龐德', titleEn: 'Pang De Bears His Coffin at Fancheng',
    introZh: '龐德抬棺出陣,誓與你麾下大將決一死戰,白袍上血漬未乾。今日不死不休!',
    introEn: 'Pang De rides out with a coffin borne before him, sworn to fight your champion to the death — his white robe still stained. Today, no quarter!',
    opponentId: 'pang-de',
    winEffects: [gold(440, '力克抬櫬死戰之龐德 — 樊城軍心大振。', 'You master the death-sworn Pang De — Fancheng takes heart.')],
    loseEffects: [note('龐德悍勇,箭傷亦不退,你勉力收兵。', 'Pang De fights on through his wounds; you withdraw with effort.')],
    slayEffects: [gold(380, '陣斬龐德,棺中人終歸棺中 — 威震樊城!', 'You cut down Pang De — the coffin claims its bearer at last!')],
  },
  {
    id: 'hanshui-zhang-he',
    kind: 'champion-challenge',
    titleZh: '漢水退張郃', titleEn: 'Turn Back Zhang He at the Han',
    introZh: '漢水之畔,張郃巧變多端,連挫蜀軍。可遣猛將,挫一挫這河間名將的鋒芒?',
    introEn: 'By the Han River, the cunning Zhang He has bloodied the Shu host. Send a champion to blunt the famed general of Hejian?',
    opponentId: 'zhang-he',
    winEffects: [gold(420, '漢水退張郃 — 蜀軍轉危為安。', 'You turn back Zhang He at the Han — the Shu host steadies.')],
    loseEffects: [note('張郃用兵巧變,你部下未能討得便宜。', 'Zhang He\'s cunning gives your champion no opening.')],
    slayEffects: [gold(380, '陣斬張郃 — 魏失一巧變之將!', 'You cut down Zhang He — Wei loses its craftiest blade!')],
  },
  {
    id: 'fengming-han-de',
    kind: 'famous-duel',
    titleZh: '鳳鳴山力斬韓德', titleEn: 'Slay Han De at Fengming',
    introZh: '鳳鳴山前,韓德父子五人列陣搦戰,欺老將年高。可教這西涼一門,知何謂老當益壯?',
    introEn: 'At Fengming Mountain, Han De and his four sons array against an aged general, thinking him spent. Teach this Xiliang house what an old tiger can still do!',
    opponentId: 'han-de',
    winEffects: [gold(400, '鳳鳴山一戰,老將揚威 — 老當益壯,傳為佳話。', 'The old tiger roars at Fengming — a tale of age undimmed.')],
    loseEffects: [note('韓德父子圍攻甚急,你殺出重圍。', 'Han De\'s sons press hard; you fight your way clear.')],
    slayEffects: [gold(360, '力斬韓德父子於鳳鳴山下 — 西涼喪膽!', 'You cut down the Han house at Fengming — Xiliang quails!')],
  },
  {
    id: 'lejia-wen-yang',
    kind: 'champion-challenge',
    titleZh: '樂嘉橋會文鴦', titleEn: 'Face Wen Yang at Lejia Bridge',
    introZh: '樂嘉橋畔,文鴦單騎殺入重圍,往來衝突,無人能擋。可敢遣將,當面領教這小將軍的神威?',
    introEn: 'At Lejia Bridge, Wen Yang charges alone into the host and back again — none can hold him. Dare you send a champion to test the young general\'s might?',
    opponentId: 'wen-yang',
    winEffects: [gold(440, '攔下單騎之文鴦 — 此戰傳唱多年。', 'You halt the lone-riding Wen Yang — a duel sung for years.')],
    loseEffects: [note('文鴦神勇,往來無礙,你部下難攖其鋒。', 'Wen Yang is unstoppable; your champion cannot close.')],
    slayEffects: [gold(400, '陣斬文鴦於樂嘉橋 — 止住這趙子龍再世之勢!', 'You cut down Wen Yang at Lejia — the new Zhao Yun is undone!')],
  },
  {
    id: 'changsha-huang-zhong',
    kind: 'grudge',
    titleZh: '戰長沙·義釋黃忠', titleEn: 'The Long Sha Duel with Huang Zhong',
    introZh: '長沙城下,老將黃忠寶刀不老,與你麾下大將鬥了百合不分勝負。今日,再決高下!',
    introEn: 'Below Changsha, the old Huang Zhong\'s blade is far from blunt — a hundred bouts with your champion and still no victor. Today, settle it!',
    opponentId: 'huang-zhong',
    winEffects: [gold(430, '長沙百合,力服老黃忠 — 英雄相惜。', 'A hundred bouts at Changsha — you master old Huang Zhong, and honour him.')],
    loseEffects: [note('黃忠寶刀沉穩,你部下未能取勝。', 'Huang Zhong\'s blade is steady; your champion cannot prevail.')],
    slayEffects: [gold(360, '長沙斬黃忠 — 然天下惜此老將之亡。', 'You fell Huang Zhong at Changsha — though the realm mourns the old hero.')],
  },
  {
    id: 'wancheng-zhang-xiu',
    kind: 'champion-challenge',
    titleZh: '宛城會北地槍王', titleEn: 'The Spear-King at Wancheng',
    introZh: '宛城張繡,師承「槍王」童淵,一桿槍出神入化。可遣猛將,會一會這北地槍王?',
    introEn: 'Zhang Xiu of Wancheng, taught by the Spear-King Tong Yuan, wields a spear beyond compare. Send a champion to face the Spear-King of the North?',
    opponentId: 'zhang-xiu',
    winEffects: [gold(400, '會北地槍王而勝之 — 槍法一道,更上層樓。', 'You best the Spear-King — and your own art climbs a rung.')],
    loseEffects: [note('張繡槍法如神,你部下落了下風。', 'Zhang Xiu\'s spear is divine; your champion is outmatched.')],
    slayEffects: [gold(340, '槍挑張繡於宛城 — 北地槍王今日折!', 'You spear Zhang Xiu at Wancheng — the Spear-King falls!')],
  },
  {
    id: 'huangxu-cao-zhang',
    kind: 'champion-challenge',
    titleZh: '會黃鬚兒曹彰', titleEn: 'Face Cao Zhang the Yellow-Beard',
    introZh: '曹彰黃鬚虬髯,力能搏虎,曹操稱其「黃鬚兒」。可敢遣將,當面領教這萬夫不當之勇?',
    introEn: 'Cao Zhang, yellow-bearded and tiger-strong, whom Cao Cao called his "Yellow-Beard." Dare you send a champion against this match-for-myriads valour?',
    opponentId: 'cao-zhang',
    winEffects: [gold(410, '挫黃鬚兒之鋒 — 曹家虎子,亦有敗時。', 'You blunt the Yellow-Beard — even Cao\'s tiger-son can be bested.')],
    loseEffects: [note('曹彰勇力絕倫,你部下難當其鋒。', 'Cao Zhang\'s strength is boundless; your champion cannot stand it.')],
    slayEffects: [gold(360, '陣斬曹彰 — 曹家折一虎子!', 'You cut down Cao Zhang — Cao loses a tiger-son!')],
  },
  {
    id: 'panhe-gongsun',
    kind: 'famous-duel',
    titleZh: '磐河會白馬將軍', titleEn: 'The White-Horse General at Panhe',
    introZh: '磐河橋畔,公孫瓚白馬銀槍,白馬義從縱橫河北。可遣猛將,當面挫這白馬將軍之威?',
    introEn: 'At Panhe Bridge, Gongsun Zan rides white with silver spear, his White-Horse Volunteers sweeping Hebei. Send a champion to blunt the White-Horse General?',
    opponentId: 'gongsun-zan',
    winEffects: [gold(400, '磐河挫公孫瓚 — 白馬義從一時奪氣。', 'You blunt Gongsun Zan at Panhe — the White-Horse riders lose heart.')],
    loseEffects: [note('公孫瓚白馬神駿,你部下追之不及。', 'Gongsun Zan\'s white steed is too swift to catch.')],
    slayEffects: [gold(340, '陣斬公孫瓚於磐河 — 白馬將軍殞命!', 'You fell Gongsun Zan at Panhe — the White-Horse General is no more!')],
  },
  {
    id: 'nanman-meng-huo',
    kind: 'champion-challenge',
    titleZh: '南中會孟獲', titleEn: 'Face Meng Huo in the South',
    introZh: '南中蠻王孟獲,身披犀甲,力大無窮,聚眾數萬與你為敵。可遣猛將,生擒這南蠻之王?',
    introEn: 'Meng Huo, king of the Nanman, clad in rhino-hide and boundlessly strong, raises tens of thousands against you. Send a champion to take the southern king?',
    opponentId: 'meng-huo',
    winEffects: [gold(380, '會孟獲而勝之 — 南中震服,可徐圖攻心。', 'You best Meng Huo — the south is shaken, and may yet be won by the heart.')],
    loseEffects: [note('孟獲勇力過人,你部下未能制之。', 'Meng Huo\'s brute strength holds; your champion cannot subdue him.')],
    slayEffects: [gold(300, '陣斬孟獲 — 然殺之易,服其心難。', 'You slay Meng Huo — yet to kill him is easy; to win his heart, hard.')],
  },
  {
    id: 'chencang-hao-zhao',
    kind: 'champion-challenge',
    titleZh: '陳倉攻郝昭', titleEn: 'Storm Hao Zhao at Chencang',
    introZh: '陳倉小城,郝昭以千餘守軍力拒蜀師,雲梯衝車皆破。可遣猛將,叩開這死守之門?',
    introEn: 'At tiny Chencang, Hao Zhao holds against the Shu host with barely a thousand men — siege-ladders and rams all broken. Send a champion to crack the unbroken gate?',
    opponentId: 'hao-zhao',
    winEffects: [gold(400, '挫郝昭之守 — 陳倉之圍,終見鬆動。', 'You blunt Hao Zhao\'s defence — the siege of Chencang loosens at last.')],
    loseEffects: [note('郝昭死守不退,你部下無功而返。', 'Hao Zhao yields nothing; your champion returns empty-handed.')],
    slayEffects: [gold(340, '陣斬郝昭 — 陳倉死守之魂,今日方折!', 'You fell Hao Zhao — the soul of Chencang\'s defiance breaks at last!')],
  },
  {
    id: 'ruxukou-zhu-huan',
    kind: 'champion-challenge',
    titleZh: '濡須口拒朱桓', titleEn: 'Break Zhu Huan at Ruxu',
    introZh: '濡須口畔,朱桓以寡敵眾,攻守相生,連挫魏軍。可遣猛將,當面挫其銳氣?',
    introEn: 'At Ruxu Mouth, Zhu Huan turns few against many, bulwark and sally as one, bloodying the Wei host. Send a champion to break his edge?',
    opponentId: 'zhu-huan',
    winEffects: [gold(390, '挫朱桓之銳 — 濡須之勢,稍可轉圜。', 'You blunt Zhu Huan — the tide at Ruxu may yet turn.')],
    loseEffects: [note('朱桓攻守得宜,你部下討不得便宜。', 'Zhu Huan gives no opening; your champion gains nothing.')],
    slayEffects: [gold(330, '陣斬朱桓 — 江東又失一棟梁!', 'You cut down Zhu Huan — Jiangdong loses another mainstay!')],
  },
  {
    id: 'maicheng-ma-zhong',
    kind: 'grudge',
    titleZh: '麥城路·馬忠設伏', titleEn: 'Ma Zhong\'s Ambush on the Maicheng Road',
    introZh: '麥城突圍之路,馬忠設下絆馬索與伏兵,專候名將自投羅網。可斬開這伏路之厄?',
    introEn: 'On the breakout road from Maicheng, Ma Zhong has laid trip-ropes and ambushers, waiting for a famous general to walk into the snare. Can you cut your way clear?',
    opponentId: 'ma-zhong-wu',
    winEffects: [gold(380, '斬開馬忠伏路 — 險地全身而退。', 'You cut through Ma Zhong\'s ambush — and win clear of the trap.')],
    loseEffects: [note('絆馬索起,伏兵四合,你浴血而出。', 'The trip-ropes spring, ambushers close — you fight out bloodied.')],
    slayEffects: [gold(340, '陣斬馬忠於麥城路 — 雪了擒龍之恥!', 'You slay Ma Zhong on the Maicheng road — the shame of the dragon\'s capture, avenged!')],
  },
  {
    id: 'tengjia-wutugu',
    kind: 'champion-challenge',
    titleZh: '藤甲軍兀突骨', titleEn: 'Wutugu of the Rattan Armour',
    introZh: '烏戈國主兀突骨,身長丈二,麾下藤甲軍刀箭不入,渡水不沉。可遣猛將,當面領教這蠻王神力?',
    introEn: 'Wutugu, king of Wuge, stands twelve feet tall; his rattan-armoured host turns blade and arrow alike and floats across rivers. Send a champion against the savage king\'s might?',
    opponentId: 'wutugu',
    winEffects: [gold(400, '挫兀突骨之勢 — 藤甲軍亦非無敵。', 'You blunt Wutugu — even the rattan host is not invincible.')],
    loseEffects: [note('藤甲刀槍不入,你部下難傷其分毫。', 'The rattan armour turns every blow; your champion cannot wound him.')],
    slayEffects: [gold(320, '陣斬兀突骨 — 然藤甲終須火破。', 'You fell Wutugu — though the rattan host, in the end, must burn.')],
  },
  // ── 千古名將・傳說對決(跨代歷史武將;唯該名將現世方可挑戰)──────────────
  {
    id: 'legend-xiang-yu',
    kind: 'famous-duel',
    titleZh: '烏江會西楚霸王', titleEn: 'The Overlord at Wujiang',
    introZh: '千古一霸,西楚霸王項羽提戟立馬,氣蓋萬軍。可敢以一將之身,挑這「力拔山兮」之絕世霸王?',
    introEn: 'The Overlord of Western Chu — Xiang Yu sits his horse with halberd raised, his spirit cloaking ten thousand. Dare you, with a single champion, face the peerless conqueror?',
    opponentId: 'hist-xiang-yu',
    winEffects: [gold(800, '力撼西楚霸王 — 此戰必傳千古!', 'You stand against the Overlord himself — a duel for the ages!')],
    loseEffects: [note('霸王之勇,萬人辟易,你力戰而退。', 'The Overlord\'s might scatters armies; you fight free and withdraw.')],
    slayEffects: [gold(1000, '陣斬西楚霸王 — 改寫千古之名!', 'You cut down the Overlord of Chu — and rewrite the ages!')],
  },
  {
    id: 'legend-bai-qi',
    kind: 'champion-challenge',
    titleZh: '長平會殺神白起', titleEn: 'The God of Slaughter at Changping',
    introZh: '長平故壘,武安君白起立於白骨之上,殺氣凜然。戰必勝,攻必取 —— 可敢一試這「人屠」之鋒?',
    introEn: 'On the old ramparts of Changping, Bai Qi stands amid white bones, killing-aura cold. Every battle won, every fortress taken — dare you test the "Human Butcher"\'s edge?',
    opponentId: 'hist-bai-qi',
    winEffects: [gold(700, '力克殺神白起 — 千軍辟易,威名動天!', 'You best the God of Slaughter — armies recoil, your fame shakes heaven!')],
    loseEffects: [note('白起殺氣如山,你部下難攖其鋒。', 'Bai Qi\'s killing-aura is a mountain; your champion cannot stand it.')],
    slayEffects: [gold(900, '陣斬武安君 — 殺神之名,今日易主!', 'You fell Lord Wu\'an — the God of Slaughter\'s name passes to you!')],
  },
  {
    id: 'legend-li-cunxiao',
    kind: 'famous-duel',
    titleZh: '飛虎將李存孝', titleEn: 'Li Cunxiao the Flying Tiger',
    introZh: '「王不過項,將不過李」—— 十三太保李存孝,天下無敵之名。可敢遣將,會一會這唐末第一猛將?',
    introEn: '"No king surpassed Xiang Yu; no general, Li." — Li Cunxiao, the Thirteenth Champion, unmatched under heaven. Dare you face the fiercest warrior of the late Tang?',
    opponentId: 'hist-li-cunxiao',
    winEffects: [gold(700, '力克李存孝 — 天下無敵,亦有敵手!', 'You master Li Cunxiao — even the unmatched can be matched!')],
    loseEffects: [note('李存孝神力絕倫,你部下力戰而還。', 'Li Cunxiao\'s strength is beyond compare; your champion fights free.')],
    slayEffects: [gold(900, '陣斬李存孝 — 「將不過李」,今日改寫!', 'You cut down Li Cunxiao — the old saying is rewritten today!')],
  },
  {
    id: 'legend-yue-fei',
    kind: 'champion-challenge',
    titleZh: '朱仙鎮會岳武穆', titleEn: 'Yue Fei at Zhuxian Town',
    introZh: '朱仙鎮前,岳家軍旌旗蔽日。「撼山易,撼岳家軍難」—— 可敢遣將,會一會這精忠武穆?',
    introEn: 'Before Zhuxian Town, the banners of the Yue army blot out the sun. "Easier to shake a mountain than the army of Yue." Dare you send a champion against the loyal Marshal Yue?',
    opponentId: 'hist-yue-fei',
    winEffects: [gold(700, '會岳武穆而勝之 — 槍法一道,登峰造極!', 'You best Marshal Yue — and your own art reaches its peak!')],
    loseEffects: [note('岳飛槍法如神,你部下落了下風。', 'Yue Fei\'s spear is divine; your champion is outmatched.')],
    slayEffects: [gold(880, '陣斬岳武穆 — 然天下共惜此忠魂之亡。', 'You fell Marshal Yue — though all the realm mourns the loyal soul.')],
  },
  {
    id: 'legend-huo-qubing',
    kind: 'famous-duel',
    titleZh: '漠北會冠軍侯', titleEn: 'The Champion Marquis in the Steppe',
    introZh: '漠北大荒,冠軍侯霍去病長驅千里,封狼居胥。「匈奴未滅,何以家為」—— 可敢會這閃電騎神?',
    introEn: 'In the northern steppe, the Champion Marquis Huo Qubing rides a thousand li, raising his banner on Wolf-Stone Mountain. Dare you face the lightning cavalry-god?',
    opponentId: 'hist-huo-qubing',
    winEffects: [gold(700, '會冠軍侯而勝之 — 騎戰之道,更上層樓!', 'You best the Champion Marquis — your horsemanship climbs higher still!')],
    loseEffects: [note('霍去病奔襲如電,你部下追之不及。', 'Huo Qubing raids like lightning; your champion cannot catch him.')],
    slayEffects: [gold(880, '陣斬冠軍侯 — 漠北烽煙,為之一靜!', 'You fell the Champion Marquis — and the steppe falls still!')],
  },
  {
    id: 'legend-genghis',
    kind: 'champion-challenge',
    titleZh: '草原會一代天驕', titleEn: 'The Pride of an Age on the Steppe',
    introZh: '無垠草原,成吉思汗彎弓立馬,鐵騎蔽野。「普天之下,皆我牧場」—— 可敢會這橫掃歐亞之天驕?',
    introEn: 'On the boundless steppe, Genghis Khan sits his horse, bow bent, iron cavalry blotting the plain. "All under heaven is my pasture." Dare you face the conqueror of two continents?',
    opponentId: 'hist-genghis',
    winEffects: [gold(800, '草原折服一代天驕 — 此名動四海!', 'You best the Pride of an Age on the steppe — your name shakes the world!')],
    loseEffects: [note('蒙古鐵騎如潮,你部下且戰且退。', 'The Mongol horse rolls like a tide; your champion gives ground.')],
    slayEffects: [gold(1000, '陣斬成吉思汗 — 改寫歐亞之命運!', 'You cut down Genghis Khan — and rewrite the fate of two continents!')],
  },
  {
    id: 'legend-tang-taizong',
    kind: 'champion-challenge',
    titleZh: '虎牢會天策上將', titleEn: 'Heaven\'s Strategist at Hulao',
    introZh: '虎牢關前,天策上將李世民玄甲鐵騎列陣,三千破十萬。可敢遣將,會一會這定鼎之主?',
    introEn: 'Before Hulao Pass, Li Shimin\'s black-armoured cavalry arrays — three thousand to break a hundred thousand. Dare you send a champion against the empire-founder?',
    opponentId: 'hist-tang-taizong',
    winEffects: [gold(760, '會天策上將而勝之 — 玄甲軍前,揚名立威!', 'You best Heaven\'s Strategist — fame won before the black-armoured host!')],
    loseEffects: [note('玄甲鐵騎神出鬼沒,你部下難覓其鋒。', 'The black-armoured riders strike like ghosts; your champion finds no opening.')],
    slayEffects: [gold(920, '陣斬天策上將 — 然此舉令天下扼腕。', 'You fell Heaven\'s Strategist — though the realm gasps at the loss.')],
  },
  {
    id: 'legend-lanlingwang',
    kind: 'famous-duel',
    titleZh: '金墉會蘭陵王', titleEn: 'The Prince of Lanling at Jinyong',
    introZh: '金墉城下,蘭陵王戴面具單騎陷陣,所向披靡,將士為之歌《蘭陵入陣曲》。可敢會這俊美猛將?',
    introEn: 'Below Jinyong, the masked Prince of Lanling charges alone into the host, irresistible, his men singing the "Prince of Lanling\'s Battle Song." Dare you face the beautiful warrior?',
    opponentId: 'hist-lanlingwang',
    winEffects: [gold(720, '會蘭陵王而勝之 — 入陣之勇,亦有敵手!', 'You best the Prince of Lanling — even his charge can be met!')],
    loseEffects: [note('蘭陵王入陣如神,你部下難攖其鋒。', 'The Prince charges like a god; your champion cannot stand it.')],
    slayEffects: [gold(880, '陣斬蘭陵王 — 然《入陣曲》猶在,千古傳唱。', 'You fell the Prince of Lanling — yet his battle-song echoes down the ages.')],
  },
  {
    id: 'legend-yang-ye',
    kind: 'champion-challenge',
    titleZh: '雁門會楊無敵', titleEn: 'Yang the Invincible at Yanmen',
    introZh: '雁門關前,「楊無敵」楊業鎮守北疆,遼兵聞風喪膽。可敢遣將,會一會這威震邊關之老將?',
    introEn: 'Before Yanmen Pass, "Yang the Invincible" holds the northern border; the Liao tremble at his name. Dare you send a champion against the frontier\'s old tiger?',
    opponentId: 'hist-yang-ye',
    winEffects: [gold(720, '會楊無敵而勝之 — 邊關之名,今日易主!', 'You best Yang the Invincible — the frontier\'s legend passes to you!')],
    loseEffects: [note('楊業老當益壯,你部下未能取勝。', 'Yang Ye is old and only fiercer; your champion cannot prevail.')],
    slayEffects: [gold(880, '陣斬楊無敵 — 然忠魂碧血,千古同悲。', 'You fell Yang the Invincible — though all the ages mourn the loyal blood.')],
  },
  {
    id: 'legend-mu-guiying',
    kind: 'famous-duel',
    titleZh: '穆柯寨會穆桂英', titleEn: 'Mu Guiying of the Mu Stockade',
    introZh: '穆柯寨前,穆桂英梨花槍法出神入化,巾幗不讓鬚眉。可敢遣將,會一會這楊門女帥?',
    introEn: 'Before the Mu Stockade, Mu Guiying wields her Pear-Blossom Spear beyond compare — a woman the equal of any man. Dare you send a champion against the Yang lady-general?',
    opponentId: 'hist-mu-guiying',
    winEffects: [gold(700, '會穆桂英而勝之 — 槍法一道,大開眼界!', 'You best Mu Guiying — and your own spear-art is opened wide!')],
    loseEffects: [note('穆桂英槍法如神,你部下落了下風。', 'Mu Guiying\'s spear is divine; your champion is outmatched.')],
    slayEffects: [gold(840, '陣斬穆桂英 — 然楊門忠烈,天下同惜。', 'You fell Mu Guiying — though the realm mourns the loyal house of Yang.')],
  },
  {
    id: 'legend-li-dingguo',
    kind: 'champion-challenge',
    titleZh: '桂林會晉王李定國', titleEn: 'Li Dingguo at Guilin',
    introZh: '桂林城下,晉王李定國象陣突出,兩蹶名王,清軍為之喪膽。可敢會這南明擎天之柱?',
    introEn: 'Below Guilin, Prince Li Dingguo charges with war-elephants, having felled two Qing princes — the Qing host quails. Dare you face the pillar of the Southern Ming?',
    opponentId: 'hist-li-dingguo',
    winEffects: [gold(720, '會李定國而勝之 — 此戰必傳於後世!', 'You best Li Dingguo — a duel that will be told for ages!')],
    loseEffects: [note('李定國勇略兼備,你部下難討便宜。', 'Li Dingguo is both brave and cunning; your champion gains no edge.')],
    slayEffects: [gold(860, '陣斬晉王 — 然南明擎天之柱,就此傾頹。', 'You fell the Prince — and the last pillar of the Southern Ming falls with him.')],
  },
  {
    id: 'legend-cheng-yaojin',
    kind: 'champion-challenge',
    titleZh: '瓦崗會程咬金', titleEn: 'Cheng Yaojin of the Wagang',
    introZh: '瓦崗寨前,混世魔王程咬金三板斧名震天下,半路殺出,人皆膽寒。可敢領教這三斧之威?',
    introEn: 'Before the Wagang stronghold, Cheng Yaojin\'s "three axe-strokes" are famed across the land — he springs from the roadside and men quail. Dare you face the three axes?',
    opponentId: 'hist-cheng-yaojin',
    winEffects: [gold(620, '過得程咬金三板斧 — 一笑泯之,傳為趣談。', 'You weather Cheng Yaojin\'s three axes — and laugh it off, a tale for the taverns.')],
    loseEffects: [note('三板斧勢大力沉,你部下措手不及。', 'The three axe-strokes fall heavy and fast; your champion is caught off guard.')],
    slayEffects: [gold(560, '陣斬程咬金 — 然此福將,世人多惜。', 'You fell Cheng Yaojin — though folk are fond of the lucky old axeman.')],
  },
  {
    id: 'legend-jing-ke',
    kind: 'grudge',
    titleZh: '易水會荊軻', titleEn: 'Jing Ke at the Yi River',
    introZh: '易水蕭蕭,荊軻懷圖窮匕見之決死,圖一擊而動天下。可敢正面接下這刺客之鋒?',
    introEn: 'The Yi River sighs; Jing Ke carries a death-resolve — a dagger hidden in a map, one strike to move the world. Dare you meet the assassin head-on?',
    opponentId: 'hist-jing-ke',
    winEffects: [gold(640, '正面折服荊軻 — 刺客之利,亦難近身。', 'You best Jing Ke face-to-face — even the assassin\'s edge cannot close.')],
    loseEffects: [note('荊軻死志已決,匕首淬毒,你險而後免。', 'Jing Ke\'s death-resolve is set, his dagger poisoned; you barely win clear.')],
    slayEffects: [gold(580, '陣斬荊軻於易水 — 風蕭蕭兮,壯士不還。', 'You cut down Jing Ke at the Yi — the wind sighs, the brave man does not return.')],
  },
  {
    id: 'luofeng-zhang-ren',
    kind: 'grudge',
    titleZh: '落鳳坡會張任', titleEn: 'Zhang Ren at Phoenix Slope',
    introZh: '落鳳坡前,張任伏弩以待,一箭射落鳳雛。蜀軍上下,誓報此仇 —— 可敢正面會這蜀中名將?',
    introEn: 'At Phoenix Slope, Zhang Ren waits with hidden crossbows — one shaft felled the Fledgling Phoenix. The Shu host swears vengeance. Dare you face the champion of Shu head-on?',
    opponentId: 'zhang-ren',
    winEffects: [gold(420, '正面折服張任 — 蜀軍鬱氣,為之一伸。', 'You best Zhang Ren face-to-face — the Shu host\'s grief is eased.')],
    loseEffects: [note('張任弩箭精準,你部下不敢輕進。', 'Zhang Ren\'s crossbow is deadly accurate; your champion dares not press.')],
    slayEffects: [gold(380, '陣斬張任於落鳳坡 — 鳳雛之仇,今日得報!', 'You fell Zhang Ren at Phoenix Slope — the Fledgling Phoenix is avenged!')],
  },
  {
    id: 'legend-zheng-chenggong',
    kind: 'champion-challenge',
    titleZh: '東海會國姓爺', titleEn: 'Koxinga of the Eastern Sea',
    introZh: '東海之上,國姓爺鄭成功樓船蔽海,跨海東征,逐荷復土。可敢遣將,會一會這海上孤忠?',
    introEn: 'On the Eastern Sea, Koxinga\'s tower-ships blot the water — crossing the strait to drive out the Dutch and reclaim the land. Dare you face the lone loyalist of the seas?',
    opponentId: 'hist-zheng-chenggong',
    winEffects: [gold(700, '會國姓爺而勝之 — 海上之名,傳於後世!', 'You best Koxinga — a name carried down the ages of the sea!')],
    loseEffects: [note('鄭成功水陸俱精,你部下難討便宜。', 'Koxinga is master of land and sea; your champion gains no edge.')],
    slayEffects: [gold(840, '陣斬國姓爺 — 然海上孤忠,千古同欽。', 'You fell Koxinga — though the ages honour the lone loyalist of the seas.')],
  },
  {
    id: 'legend-xie-xuan',
    kind: 'champion-challenge',
    titleZh: '淝水會謝玄', titleEn: 'Xie Xuan at the Fei River',
    introZh: '淝水之畔,謝玄統北府勁旅,八萬破百萬,談笑卻敵。可敢遣將,會一會這名門虎將?',
    introEn: 'By the Fei River, Xie Xuan leads the elite Beifu Army — eighty thousand to break a million, the foe routed between a laugh and a word. Dare you face the noble-born tiger?',
    opponentId: 'hist-xie-xuan',
    winEffects: [gold(700, '會謝玄而勝之 — 北府之名,亦有敵手!', 'You best Xie Xuan — even the Beifu has met its match!')],
    loseEffects: [note('謝玄用兵如神,你部下風聲鶴唳。', 'Xie Xuan\'s command is divine; your champion takes every reed for a soldier.')],
    slayEffects: [gold(840, '陣斬謝玄 — 然北府忠勇,天下同惜。', 'You fell Xie Xuan — though the realm mourns the loyal Beifu host.')],
  },
  {
    id: 'mianzhu-zhuge-zhan',
    kind: 'grudge',
    titleZh: '綿竹會諸葛尚父子', titleEn: 'The Zhuge Stand at Mianzhu',
    introZh: '綿竹關前,諸葛瞻父子身殉社稷,有死無降。鄧艾大軍壓境 —— 可敢正面領教這忠烈之鋒?',
    introEn: 'Before Mianzhu Pass, Zhuge Zhan and his son give their lives for the realm — death before surrender. Deng Ai\'s host bears down. Dare you face the loyal blood head-on?',
    opponentId: 'zhuge-zhan',
    winEffects: [gold(440, '會諸葛瞻而勝之 — 忠烈雖敗,猶為人敬。', 'You best Zhuge Zhan — the loyal blood, though beaten, is honoured still.')],
    loseEffects: [note('諸葛瞻死戰不退,你部下難以速勝。', 'Zhuge Zhan fights on to the death; your champion cannot win quickly.')],
    slayEffects: [gold(380, '陣斬諸葛瞻於綿竹 — 然武侯一脈,天下同悲。', 'You fell Zhuge Zhan at Mianzhu — though the realm mourns the Marquis\'s line.')],
  },
  {
    id: 'legend-zhang-xun',
    kind: 'champion-challenge',
    titleZh: '睢陽會張巡', titleEn: 'Zhang Xun at Suiyang',
    introZh: '睢陽孤城,張巡以數千殘卒死守經年,屏蔽江淮。嚼齒穿齦,誓不降賊 —— 可敢會這死守孤忠?',
    introEn: 'In the lone city of Suiyang, Zhang Xun holds for a year with a few thousand worn men, shielding the south. He grinds his teeth to splinters, sworn never to yield. Dare you face the death-holding loyalist?',
    opponentId: 'hist-zhang-xun',
    winEffects: [gold(640, '會張巡而勝之 — 然孤城死守之忠,千古同欽。', 'You best Zhang Xun — though the ages honour the lone city\'s loyalty.')],
    loseEffects: [note('張巡死志已決,你部下難撼孤城。', 'Zhang Xun\'s death-resolve is set; your champion cannot shake the lone city.')],
    slayEffects: [gold(560, '陣斬張巡 — 然守一城捍天下之名,永垂青史。', 'You fell Zhang Xun — yet "he held one city and shielded the realm" lives forever.')],
  },
  {
    id: 'legend-li-zicheng',
    kind: 'champion-challenge',
    titleZh: '潼關會闖王李自成', titleEn: 'The Dashing King at Tong Pass',
    introZh: '潼關之下,闖王李自成百萬之眾,「迎闖王,不納糧」,直搗京師。可敢遣將,會一會這顛覆天下之雄?',
    introEn: 'Below Tong Pass, the Dashing King Li Zicheng leads a host of a million — "Welcome the Dashing King, pay no grain" — driving for the capital. Dare you face the realm-toppling rebel?',
    opponentId: 'hist-li-zicheng',
    winEffects: [gold(680, '會闖王而勝之 — 此戰必為後世所記!', 'You best the Dashing King — a duel the future will remember!')],
    loseEffects: [note('闖軍勢大,你部下且戰且退。', 'The Dashing army\'s momentum is great; your champion gives ground.')],
    slayEffects: [gold(820, '陣斬闖王 — 然明清易代之勢,豈一人可挽?', 'You fell the Dashing King — though could one man stem the tide of an age?')],
  },
  {
    id: 'legend-wang-xuance',
    kind: 'champion-challenge',
    titleZh: '天竺會王玄策', titleEn: 'Wang Xuance in India',
    introZh: '天竺之地,大唐使節王玄策借兵數千,一人滅一國,生擒其主。可敢會這縱橫異域之奇士?',
    introEn: 'In the land of India, the Tang envoy Wang Xuance borrows a few thousand troops and topples a kingdom single-handed, taking its king alive. Dare you face the wanderer who ranged the foreign realms?',
    opponentId: 'hist-wang-xuance',
    winEffects: [gold(660, '會王玄策而勝之 — 縱橫之士,亦有敵手!', 'You best Wang Xuance — even the great wanderer has met his match!')],
    loseEffects: [note('王玄策智勇兼備,你部下難以取勝。', 'Wang Xuance is both brave and cunning; your champion cannot prevail.')],
    slayEffects: [gold(720, '陣斬王玄策 — 然一人滅國之名,千古傳奇。', 'You fell Wang Xuance — yet "one man toppled a kingdom" is a legend for the ages.')],
  },
  {
    id: 'legend-zhu-yuanzhang',
    kind: 'champion-challenge',
    titleZh: '鄱陽會明太祖', titleEn: 'The Ming Founder at Poyang',
    introZh: '鄱陽湖上,朱元璋與陳友諒六十萬大軍決戰,火攻連環,一戰定鼎。可敢遣將,會一會這布衣天子?',
    introEn: 'On Lake Poyang, Zhu Yuanzhang fights Chen Youliang\'s six hundred thousand in a decisive battle of fire-ships, settling the realm in a stroke. Dare you face the peasant-born emperor?',
    opponentId: 'hist-zhu-yuanzhang',
    winEffects: [gold(760, '會明太祖而勝之 — 此戰必傳於青史!', 'You best the Ming Founder — a duel for the chronicles!')],
    loseEffects: [note('朱元璋雄才大略,你部下難討便宜。', 'Zhu Yuanzhang is a master of grand strategy; your champion gains no edge.')],
    slayEffects: [gold(920, '陣斬明太祖 — 然開國之勢,豈一人可阻?', 'You fell the Ming Founder — though could one man halt the founding of a dynasty?')],
  },
  {
    id: 'legend-tian-heng',
    kind: 'grudge',
    titleZh: '海島會田橫', titleEn: 'Tian Heng on the Isle',
    introZh: '海島之上,田橫與五百壯士義不帝秦,寧死不屈。可敢會這義薄雲天之豪傑?',
    introEn: 'On a sea-isle, Tian Heng and his five hundred brave men refuse to bow to the usurper, choosing death over dishonour. Dare you face the hero of boundless honour?',
    opponentId: 'hist-tian-heng',
    winEffects: [gold(600, '會田橫而勝之 — 然其義氣,某亦敬之。', 'You best Tian Heng — yet his honour you cannot help but respect.')],
    loseEffects: [note('田橫義士死戰,你部下難撼其志。', 'Tian Heng\'s righteous men fight to the death; your champion cannot shake their resolve.')],
    slayEffects: [gold(520, '陣斬田橫 — 然五百義士,聞之皆自刎。', 'You fell Tian Heng — and his five hundred, hearing of it, fall on their own swords.')],
  },
  {
    id: 'legend-sun-wu',
    kind: 'champion-challenge',
    titleZh: '吳宮會兵聖孫武', titleEn: 'Sun Tzu at the Palace of Wu',
    introZh: '吳宮校場,兵聖孫武以《兵法》十三篇見吳王,治兵如神,賞罰分明。可敢會這百世兵家之祖?',
    introEn: 'On the drill-ground of the Wu palace, the Sage of War Sun Wu presents his thirteen chapters to the King — his command divine, reward and punishment exact. Dare you face the founder of all military art?',
    opponentId: 'hist-sun-wu',
    winEffects: [gold(760, '會兵聖而勝之 — 兵法一道,豁然貫通!', 'You best the Sage of War — and the art of war opens clear before you!')],
    loseEffects: [note('孫武用兵如神,你部下動輒受制。', 'Sun Wu\'s command is divine; your champion is checked at every turn.')],
    slayEffects: [gold(820, '陣斬兵聖 — 然《孫子》十三篇,萬世不朽。', 'You fell the Sage — yet the thirteen chapters endure for all time.')],
  },
  {
    id: 'legend-li-yuan',
    kind: 'champion-challenge',
    titleZh: '晉陽會唐高祖', titleEn: 'The Tang Founder at Jinyang',
    introZh: '晉陽城下,唐國公李淵太原起兵,直入長安,開創大唐三百年基業。可敢遣將,會一會這開國之君?',
    introEn: 'Below Jinyang, Duke Li Yuan of Tang rises at Taiyuan and drives into Chang\'an, founding three centuries of the great Tang. Dare you send a champion against the dynasty\'s founder?',
    opponentId: 'hist-li-yuan',
    winEffects: [gold(720, '會唐高祖而勝之 — 此戰必傳於青史!', 'You best the Tang Founder — a duel for the chronicles!')],
    loseEffects: [note('李淵帝王之資,你部下難討便宜。', 'Li Yuan has the bearing of an emperor; your champion gains no edge.')],
    slayEffects: [gold(880, '陣斬唐高祖 — 然大唐立國之勢,豈一人可阻?', 'You fell the Tang Founder — though could one man halt the founding of the Tang?')],
  },
  {
    id: 'legend-zuo-zongtang',
    kind: 'champion-challenge',
    titleZh: '西征會左宗棠', titleEn: 'Zuo Zongtang\'s March West',
    introZh: '大漠西陲,左宗棠抬棺出征,誓復新疆,寸土不讓。可敢會這「身無半畝、心憂天下」之名臣?',
    introEn: 'On the western desert frontier, Zuo Zongtang marches bearing his own coffin, sworn to reclaim Xinjiang and yield not one foot of soil. Dare you face the statesman who owned not half an acre, yet carried the realm in his heart?',
    opponentId: 'hist-zuo-zongtang',
    winEffects: [gold(700, '會左宗棠而勝之 — 然其抬棺之志,令人肅然。', 'You best Zuo Zongtang — yet his coffin-borne resolve commands awe.')],
    loseEffects: [note('左宗棠意志如鐵,你部下難撼其鋒。', 'Zuo Zongtang\'s will is iron; your champion cannot shake him.')],
    slayEffects: [gold(760, '陣斬左宗棠 — 然收復新疆之功,後世長記。', 'You fell Zuo Zongtang — yet the ages remember the reclaiming of Xinjiang.')],
  },
  {
    id: 'legend-chen-youliang',
    kind: 'grudge',
    titleZh: '鄱陽湖會陳友諒', titleEn: 'Chen Youliang on Lake Poyang',
    introZh: '鄱陽湖上,陳漢皇帝陳友諒巨艦連環,六十萬眾蔽江而來。可敢遣將,會一會這朱元璋之勁敵?',
    introEn: 'On Lake Poyang, the Chen-Han Emperor Chen Youliang chains his giant ships, six hundred thousand strong, blotting the river. Dare you face Zhu Yuanzhang\'s great rival?',
    opponentId: 'hist-chen-youliang',
    winEffects: [gold(720, '會陳友諒而勝之 — 鄱陽之上,揚名立威!', 'You best Chen Youliang — fame won upon Lake Poyang!')],
    loseEffects: [note('陳友諒巨艦如山,你部下難以撼動。', 'Chen Youliang\'s ships are mountains; your champion cannot move them.')],
    slayEffects: [gold(860, '陣斬陳友諒 — 元末爭雄,塵埃落定!', 'You fell Chen Youliang — and the contest for the realm is settled!')],
  },
  {
    id: 'legend-huang-chao',
    kind: 'champion-challenge',
    titleZh: '長安會沖天大將軍', titleEn: 'The Heaven-Storming General at Chang\'an',
    introZh: '長安城下,黃巢「滿城盡帶黃金甲」,沖天香陣,百萬之眾席捲天下。可敢會這顛覆大唐之梟雄?',
    introEn: 'Below Chang\'an, Huang Chao\'s host — "the whole city clad in golden armour" — sweeps the realm a million strong. Dare you face the rebel who toppled the Tang?',
    opponentId: 'hist-huang-chao',
    winEffects: [gold(680, '會黃巢而勝之 — 沖天之勢,亦有敵手!', 'You best Huang Chao — even the heaven-storming tide has met its match!')],
    loseEffects: [note('黃巢百萬之眾,你部下且戰且退。', 'Huang Chao\'s million press on; your champion gives ground.')],
    slayEffects: [gold(820, '陣斬黃巢 — 然大唐傾頹之勢,豈一人可挽?', 'You fell Huang Chao — though could one man stem the fall of the Tang?')],
  },
  {
    id: 'legend-helu',
    kind: 'champion-challenge',
    titleZh: '柏舉會吳王闔閭', titleEn: 'King Helu of Wu at Boju',
    introZh: '柏舉之戰,吳王闔閭用孫武、伍子胥之謀,五戰入郢,幾滅強楚。可敢會這春秋霸主?',
    introEn: 'At the Battle of Boju, King Helu of Wu, counselled by Sun Wu and Wu Zixu, wins five battles into Ying and nearly ends mighty Chu. Dare you face the Spring-and-Autumn hegemon?',
    opponentId: 'hist-helu',
    winEffects: [gold(700, '會吳王闔閭而勝之 — 春秋霸業,亦有敵手!', 'You best King Helu — even a hegemon\'s might has met its match!')],
    loseEffects: [note('闔閭兵精將良,你部下難以取勝。', 'Helu\'s troops and generals are elite; your champion cannot prevail.')],
    slayEffects: [gold(820, '陣斬吳王闔閭 — 然吳越爭霸,猶未有窮期。', 'You fell King Helu — though the struggle of Wu and Yue is far from over.')],
  },
  {
    id: 'chibi-zhou-yu',
    kind: 'grudge',
    titleZh: '赤壁會周郎', titleEn: 'Zhou Yu at Red Cliff',
    introZh: '赤壁江上,周瑜談笑用兵,東風一起,曹軍檣櫓灰飛煙滅。可敢遣將,會一會這江東美周郎?',
    introEn: 'On the river at Red Cliff, Zhou Yu commands between a laugh and a word — the east wind rises, and Cao\'s fleet turns to ash. Dare you send a champion against the handsome Zhou Lang of the south?',
    opponentId: 'zhou-yu',
    winEffects: [gold(520, '會周郎而勝之 — 然其雅量高致,某亦敬之。', 'You best Zhou Lang — yet his grace and brilliance you cannot but admire.')],
    loseEffects: [note('周瑜運籌帷幄,你部下落了下風。', 'Zhou Yu plots within the tent; your champion is outmaneuvered.')],
    slayEffects: [gold(480, '陣斬周瑜 — 然「既生瑜何生亮」之嘆,千古猶聞。', 'You fell Zhou Yu — yet his lament echoes through the ages.')],
  },
  {
    id: 'feishui-fu-jian',
    kind: 'champion-challenge',
    titleZh: '淝水會苻堅', titleEn: 'Fu Jian at the Fei River',
    introZh: '淝水之畔,大秦天王苻堅統百萬之眾,「投鞭可斷流」,然風聲鶴唳,草木皆兵。可敢會這前秦霸主?',
    introEn: 'By the Fei River, Fu Jian, Heavenly King of Qin, leads a host of a million — "whips enough to dam the river" — yet wind and crane-cries turn every reed to a soldier. Dare you face the Former-Qin overlord?',
    opponentId: 'hist-fu-jian',
    winEffects: [gold(700, '會苻堅而勝之 — 百萬之眾,亦有敵手!', 'You best Fu Jian — even a host of a million has met its match!')],
    loseEffects: [note('苻堅兵多將廣,你部下且戰且退。', 'Fu Jian\'s host is vast; your champion gives ground.')],
    slayEffects: [gold(840, '陣斬苻堅 — 然淝水之敗,豈一人之過?', 'You fell Fu Jian — though was the rout at the Fei the fault of one man?')],
  },
  {
    id: 'baipao-chen-qingzhi',
    kind: 'champion-challenge',
    titleZh: '白袍會陳慶之', titleEn: 'Chen Qingzhi of the White Robes',
    introZh: '「名師大將莫自牢,千兵萬馬避白袍。」陳慶之以七千白袍之師,連下三十二城。可敢會這儒將奇才?',
    introEn: '"Let no famed general boast — a thousand horse flee the white robe." Chen Qingzhi, with seven thousand white-robed men, took thirty-two cities in a row. Dare you face the scholar-general\'s genius?',
    opponentId: 'hist-chen-qingzhi',
    winEffects: [gold(720, '會白袍陳慶之而勝之 — 七千之師,亦有敵手!', 'You best Chen Qingzhi — even his seven thousand has met its match!')],
    loseEffects: [note('陳慶之用兵如神,你部下難覓其鋒。', 'Chen Qingzhi\'s command is divine; your champion finds no opening.')],
    slayEffects: [gold(860, '陣斬陳慶之 — 然白袍之名,千古傳奇。', 'You fell Chen Qingzhi — yet the white robe remains a legend of the ages.')],
  },
];

// ─── 單挑戰役 (duel campaign) — a curated chain of famous duels in story order.
// A step unlocks once the previous step is cleared (and its foe is on the field).
// Pure framing over the scenarios above; progress is tracked by the store.
export interface DuelCampaign { id: string; titleZh: string; titleEn: string; steps: string[]; }
export const DUEL_CAMPAIGNS: DuelCampaign[] = [
  {
    id: 'rise-of-a-champion',
    titleZh: '虎將之路', titleEn: 'Path of the Tiger General',
    steps: ['slay-hua-xiong', 'three-vs-lubu', 'slay-yan-liang', 'jiameng-pass', 'tiger-zhang-liao'],
  },
  {
    id: 'duels-of-legend',
    titleZh: '萬人敵之名', titleEn: 'Name of a Myriad-Foe',
    steps: ['slay-yan-liang', 'slay-wen-chou', 'shenting-taishici', 'tong-pass-xuchu', 'jiange-gan-ning'],
  },
  {
    id: 'generals-deathmatch',
    titleZh: '名將生死鬥', titleEn: 'Deathmatch of Champions',
    steps: ['dingjun-xiahou-yuan', 'fancheng-pang-de', 'hanshui-zhang-he', 'fengming-han-de', 'lejia-wen-yang'],
  },
  {
    id: 'warlords-of-the-realm',
    titleZh: '亂世群雄', titleEn: 'Warlords of the Realm',
    steps: ['panhe-gongsun', 'wancheng-zhang-xiu', 'changsha-huang-zhong', 'huangxu-cao-zhang', 'nanman-meng-huo'],
  },
  {
    id: 'siege-and-snare',
    titleZh: '攻堅破伏', titleEn: 'Siege and Snare',
    steps: ['chencang-hao-zhao', 'ruxukou-zhu-huan', 'maicheng-ma-zhong', 'tengjia-wutugu'],
  },
  {
    id: 'legends-of-the-ages',
    titleZh: '千古名將', titleEn: 'Legends of the Ages',
    steps: ['legend-xiang-yu', 'legend-bai-qi', 'legend-li-cunxiao', 'legend-yue-fei', 'legend-huo-qubing'],
  },
  {
    id: 'emperors-and-khans',
    titleZh: '帝王雄主', titleEn: 'Emperors and Khans',
    steps: ['legend-tang-taizong', 'legend-genghis', 'legend-lanlingwang', 'legend-yang-ye'],
  },
  {
    id: 'heroes-and-assassins',
    titleZh: '俠骨刺客', titleEn: 'Heroes and Assassins',
    steps: ['legend-jing-ke', 'legend-mu-guiying', 'legend-cheng-yaojin', 'legend-li-dingguo'],
  },
  {
    id: 'tigers-of-every-age',
    titleZh: '歷代名帥', titleEn: 'Marshals of Every Age',
    steps: ['luofeng-zhang-ren', 'legend-xie-xuan', 'legend-zheng-chenggong'],
  },
  {
    id: 'loyalty-and-rebellion',
    titleZh: '忠魂逆鱗', titleEn: 'Loyalty and Rebellion',
    steps: ['mianzhu-zhuge-zhan', 'legend-zhang-xun', 'legend-li-zicheng'],
  },
  {
    id: 'founders-and-wanderers',
    titleZh: '開國奇士', titleEn: 'Founders and Wanderers',
    steps: ['legend-tian-heng', 'legend-wang-xuance', 'legend-zhu-yuanzhang'],
  },
  {
    id: 'sages-and-statesmen',
    titleZh: '兵聖名臣', titleEn: 'Sages and Statesmen',
    steps: ['legend-sun-wu', 'legend-li-yuan', 'legend-zuo-zongtang'],
  },
  {
    id: 'hegemons-and-rebels',
    titleZh: '霸主梟雄', titleEn: 'Hegemons and Rebels',
    steps: ['legend-helu', 'legend-huang-chao', 'legend-chen-youliang'],
  },
  {
    id: 'strategists-of-genius',
    titleZh: '奇謀儒將', titleEn: 'Strategists of Genius',
    steps: ['chibi-zhou-yu', 'baipao-chen-qingzhi', 'feishui-fu-jian'],
  },
];

export interface CampaignStep { id: string; scenario: DuelScenario | undefined; cleared: boolean; unlocked: boolean; }
/** Resolve a campaign into per-step state given the set of cleared scenario ids. */
export function campaignSteps(campaign: DuelCampaign, cleared: ReadonlySet<string>): CampaignStep[] {
  let prevCleared = true; // the first step is always unlocked
  return campaign.steps.map((id) => {
    const isCleared = cleared.has(id);
    const step: CampaignStep = { id, scenario: DUEL_SCENARIOS_BY_ID[id], cleared: isCleared, unlocked: prevCleared };
    prevCleared = isCleared; // the NEXT step unlocks only once this one is cleared
    return step;
  });
}

export const DUEL_SCENARIOS_BY_ID: Record<string, DuelScenario> =
  Object.fromEntries(DUEL_SCENARIOS.map((s) => [s.id, s]));

/** Map a finished scenario bout to the effects a host should apply. */
export function duelScenarioOutcome(
  scenario: DuelScenario,
  result: { won: boolean; slain: boolean },
): ScenarioEffect[] {
  if (!result.won) return scenario.loseEffects;
  const effects = [...scenario.winEffects];
  if (result.slain && scenario.slayEffects) effects.push(...scenario.slayEffects);
  return effects;
}

/** A short headline for the result banner. */
export function duelScenarioResultLine(scenario: DuelScenario, result: { won: boolean; slain: boolean }): { zh: string; en: string } {
  if (!result.won) return { zh: `${scenario.titleZh} — 功敗垂成`, en: `${scenario.titleEn} — you fall short` };
  if (result.slain) return { zh: `${scenario.titleZh} — 陣斬敵將,大獲全勝!`, en: `${scenario.titleEn} — a kill, and a crushing victory!` };
  return { zh: `${scenario.titleZh} — 力克強敵!`, en: `${scenario.titleEn} — you best a mighty foe!` };
}

void gold; void note;
