import { TACTIC_DEFS } from '../../game/data/officerAttributes';
import { CatalogModal, type CatalogItem, type CatalogCategory } from './CatalogModal';

// Classify 24 tactics into 4 categories.
const TACTIC_CATEGORY: Record<string, string> = {
  charge:         'melee',
  rouse:          'melee',
  ambush:         'melee',
  'last-stand':   'melee',
  'iron-wall':    'melee',
  rush:           'melee',
  volley:         'ranged',
  crossbow:       'ranged',
  catapult:       'ranged',
  'fire-arrow':   'ranged',
  meteor:         'ranged',
  'fire-attack':  'mystic',
  'water-attack': 'mystic',
  thunder:        'mystic',
  'borrow-wind':  'mystic',
  'eight-gates':  'mystic',
  ruse:           'disrupt',
  disorder:       'disrupt',
  pitfall:        'disrupt',
  curse:          'disrupt',
  beauty:         'disrupt',
  chain:          'disrupt',
  'self-injury':  'disrupt',
  retreat:        'disrupt',
  feint:          'strategy',
  'besiege-wei':  'strategy',
  'wait-tired':   'strategy',
  'sneak-cross':  'strategy',
  'probe-snake':  'strategy',
  'lure-tiger':   'strategy',
  'loose-catch':  'strategy',
  'kill-king':    'strategy',
  'cut-supply':   'strategy',
  cicada:         'strategy',
  'far-near':     'strategy',
  'borrow-arrow': 'ranged',
  'deceive-sky':  'strategy',
  'loot-fire':    'strategy',
  'from-nothing': 'strategy',
  'watch-fire':   'strategy',
  'hide-knife':   'disrupt',
  'brick-jade':   'strategy',
  'muddy-fish':   'strategy',
  'door-thief':   'strategy',
  'tree-flower':  'disrupt',
  'guest-host':   'strategy',
  'feign-mad':    'disrupt',
  'pull-ladder':  'strategy',
  'borrow-knife': 'disrupt',
  'lead-sheep':   'strategy',
  'borrow-corpse':'strategy',
  'plum-peach':   'strategy',
  'borrow-road':  'strategy',
  'switch-beam':  'disrupt',
  'point-curse':  'disrupt',
  'plum-thirst':  'melee',
  'seven-lamp':   'mystic',
  'chu-songs':    'disrupt',
  'burn-bowang':  'mystic',
  'wooden-ox':    'strategy',
  'hair-head':    'strategy',
  'white-robe':   'disrupt',
  'song-map':     'strategy',
  'seven-grab':   'strategy',
  'tongue-war':   'strategy',
  changban:       'melee',
  'zhuge-bow':    'ranged',
  'chain-ship':   'strategy',
  'burn-yiling':  'mystic',
  'know-self':    'strategy',
  'fast-strike':  'melee',
  deception:      'disrupt',
  'attack-plans':   'strategy',
  'attack-heart':   'strategy',
  'surround-three': 'strategy',
  'subdue-no-fight':'strategy',
  'hide-light':     'strategy',
  'total-victory':  'strategy',
  'water-form':     'strategy',
  'ortho-extra':    'strategy',
  'qimen-dunjia':   'mystic',
  'star-prayer':    'mystic',
  'he-luo-tu':      'mystic',
  'five-thunder':   'mystic',
  'sneak-yinping':  'strategy',
  'nine-campaigns': 'strategy',
  'xiling-stand':   'melee',
  'feign-illness':  'disrupt',
  'iron-chain':     'ranged',
  'two-tigers':     'disrupt',
  'lure-tiger-wolf':'disrupt',
  'sow-discord-2':  'disrupt',
  'thousand-ride':  'melee',
  'lone-blade':     'melee',
  'pass-six':       'melee',
  'burn-xinye':     'mystic',
  'solid-camp':     'strategy',
  'death-ground':   'melee',
  'siege-relief':   'strategy',
  bloodless:        'strategy',
  // ── Phase 60 ──
  'plan-war':       'strategy',
  'cavalry-war':    'melee',
  'naval-war':      'ranged',
  'trust-war':      'strategy',
  'many-war':       'strategy',
  'few-war':        'strategy',
  'mountain-war':   'strategy',
  'night-war':      'disrupt',
  'supply-war':     'strategy',
  'defend-war':     'melee',
  'fire-ox':        'mystic',
  'sand-dam':       'mystic',
  'ban-chao':       'melee',
  'mass-burial':    'melee',
  'long-ride':      'melee',
  surprise:         'disrupt',
  unguarded:        'disrupt',
  'wind-forest':    'melee',
  'quick-decision': 'melee',
  protracted:       'strategy',
  'warm-wine':      'melee',
  'three-fight-lubu':'melee',
  'plum-wine':      'strategy',
  longzhong:        'strategy',
  'burn-chibi':     'mystic',
  'lose-jingzhou':  'disrupt',
  'flee-maicheng':  'melee',
  'white-emperor':  'strategy',
  'tearful-ma':     'strategy',
  'wuzhang-star':   'mystic',
  memorial:         'strategy',
  'edict-belt':     'disrupt',
  'borrow-jingzhou':'strategy',
  diaochan:         'disrupt',
  'liu-bei-share-meat':'strategy',
  'no-clash':       'strategy',
  'mind-might':     'strategy',
  'reverse-encircle':'melee',
  'flower-bloom':   'melee',
  annihilate:       'melee',
  attrition:        'strategy',
  'scorched-earth': 'strategy',
  'siege-starve':   'strategy',
  'break-encircle': 'melee',
  'bait-trap':      'disrupt',
  'encircle-no-attack':'strategy',
  'heart-war':      'strategy',
  'counter-plot':   'disrupt',
  'press-pursuit':  'melee',
  'still-vs-motion':'strategy',
  // ── Phase 61 ──
  'plan-state':         'strategy',
  'assess-enemy':       'strategy',
  'govern-troops':      'strategy',
  'on-generalship':     'strategy',
  'adapt-change':       'strategy',
  'inspire-soldiers':   'strategy',
  'benevolence-root':   'strategy',
  'emperor-duty':       'strategy',
  'set-ranks':          'strategy',
  'strict-position':    'strategy',
  'use-many':           'strategy',
  'five-virtues':       'strategy',
  'authority-war':      'strategy',
  'know-nature':        'strategy',
  'when-not-fight':     'strategy',
  'observe-general':    'strategy',
  'eagle-strike':       'melee',
  'tiger-crouch':       'melee',
  'leopard-wolf':       'melee',
  'crane-chickens':     'melee',
  'snake-rat':          'disrupt',
  'bee-swarm':          'melee',
  'ant-siege':          'melee',
  'whale-silk':         'strategy',
  'half-cross':         'melee',
  'array-wait':         'melee',
  'conserve-strength':  'strategy',
  'high-ground':        'melee',
  'mountain-back':      'strategy',
  'intercept-relief':   'melee',
  'rush-supply':        'disrupt',
  'feign-defeat':       'disrupt',
  'set-ambush-path':    'disrupt',
  'quick-night':        'disrupt',
  'star-reading':       'mystic',
  'tortoise-shell':     'mystic',
  'elements-counter':   'mystic',
  talisman:             'mystic',
  'summon-spirits':     'mystic',
  'julu-battle':        'melee',
  'muye-battle':        'melee',
  'chengpu-battle':     'strategy',
  'hanzhong-battle':    'melee',
  'lose-jieting':       'strategy',
  'zhao-yun-baby':      'melee',
  'huang-zhong-dingjun':'melee',
  'zhou-yu-plan':       'strategy',
  'seek-talent':        'strategy',
  'he-jin-blunder':     'disrupt',
};

const TACTIC_DESC: Record<string, string> = {
  charge:         '突擊 — 騎兵衝鋒突破敵陣。對未防禦的密集步兵殺傷尤甚。',
  rouse:          '鼓舞 — 提振士氣，使己方部隊一回合內 +20% 戰力。',
  ambush:         '急襲 — 出其不意，繞至敵後造成 25% 額外傷害。',
  volley:         '齊射 — 弓兵集體射擊，遠程齊發。對輕甲尤其有效。',
  crossbow:       '連弩 — 連發弩箭，穿透重甲。射程 +1。',
  catapult:       '投石 — 巨石投擲，攻城專用。對城牆造成額外損害。',
  'fire-attack':  '火計 — 火攻燒營，乘風縱火。順風時威力 +35%。',
  'water-attack': '水計 — 掘堤淹城，水攻陣地。要求臨水城池。',
  ruse:           '偽計 — 詐降詐敗誘敵深入，敵 INT <70 時必中。',
  disorder:       '撹亂 — 散布謠言使敵軍陷入混亂，−1 行動點。',
  pitfall:        '落穴 — 設伏陷阱，林地 / 山地專用，造成數倍傷害。',
  curse:          '罵聲 — 陣前痛罵激怒對方主將，引發魯莽行動。',
  // ── Phase 54 expansion ──
  'last-stand':   '死戰 — 兵力降至 30% 以下時觸發。武力 +30，自損 −20%。背水一戰之勢。',
  'iron-wall':    '鐵壁 — 重甲列陣，全員防御 +50%。對近戰傷害減半，但機動 −2。',
  rush:           '突進 — 騎兵兩段衝鋒。第一回合移動 +2，貫穿後排弱兵。',
  'fire-arrow':   '火矢 — 弓箭裹油點燃。命中時 30% 機率使目標 burning 3 回合。',
  meteor:         '流星 — 巨石抛射，落點殺傷一片。+20% 範圍傷害，攻城傷害翻倍。',
  thunder:        '雷震 — 道家雷法。命中目標暈眩 1 回合（−1 AP），對甲胄單位效果加倍。',
  'borrow-wind':  '借東風 — 七星壇求風，秋冬之季可成。次 2 回合內天氣強制為東風強勁。',
  'eight-gates':  '八門遁甲 — 道家陣門遁形。己方一回合內隱形難擊中，順便驅散敵方所有 buff。',
  beauty:         '美人計 — 美人遣往敵陣。敵將魅力 <70 時，10% 機率倒戈到我方。',
  chain:          '連環計 — 多重計策串接，破陣後敵全軍受三段 debuff（−攻 / −防 / −士氣）。',
  'self-injury':  '苦肉計 — 黃蓋詐降之術。犧牲己方一員，敵主將被引入致命陷阱。',
  retreat:        '走為上 — 安全撤退。我方部隊 0 損失退出戰場，但放棄當前目標。',
  // ── Phase 55: 三十六計 ──
  feint:          '聲東擊西 — 攻其無備。一回合內擾亂敵防線，使其判斷錯誤，主攻方向 +30% 傷害。',
  'besiege-wei':  '圍魏救趙 — 攻其必救。對敵主城施壓，引敵回援，解我方城被圍之困。',
  'wait-tired':   '以逸待勞 — 養精蓄銳。一回合不動，下回合所有反擊傷害 +50%。',
  'sneak-cross':  '暗渡陳倉 — 明修棧道暗渡之計。看似強攻一處，實則從未防之側突入。',
  'probe-snake':  '打草驚蛇 — 試探敵情。揭示敵下回合所有行動意圖。',
  'lure-tiger':   '調虎離山 — 誘使敵主力出城。敵守將 War ≥ 85 時優先離開原位。',
  'loose-catch':  '欲擒故縱 — 七擒之術。佯敗誘敵深入，敵追擊時觸發致命反伏。',
  'kill-king':    '擒賊擒王 — 直取主將。突襲敵主將，無視前排（要求 War ≥ 90）。',
  'cut-supply':   '釜底抽薪 — 斷其糧道。敵兵每回合自損 5%，持續 3 回合。',
  cicada:         '金蟬脫殼 — 偽裝替身脫身。我方留下虛位，主力悄然轉移。',
  'far-near':     '遠交近攻 — 範睢戰國之計。+30% 與遠方勢力建交成功率，鄰國敵意 +10。',
  'borrow-arrow': '草船借箭 — 諸葛之妙。霧天用草船誘敵射箭，反獲敵箭萬支，下回合弓兵 +50%。',
  'deceive-sky':  '瞞天過海 — 大智若愚之術。明擺於眾目，反而被忽略。本回合行動敵方視而不見。',
  'loot-fire':    '趁火打劫 — 乘敵內亂之機。敵勢力陷入叛亂 / 瘟疫時，攻擊傷害 +40%。',
  'from-nothing': '無中生有 — 虛實相生。製造假象兵力，使敵將判斷錯誤，分兵應對。',
  'watch-fire':   '隔岸觀火 — 坐山觀虎鬥。當敵國互相內戰時，本方資源每回合 +15%。',
  'hide-knife':   '笑裡藏刀 — 假意修好暗中圖之。對盟友突襲時，敵方無防備傷害 +50%。',
  'brick-jade':   '拋磚引玉 — 以小換大。捨棄一座低價值城池，換取敵主力深入後的反包圍。',
  'muddy-fish':   '渾水摸魚 — 亂中取勝。戰場混亂回合中，所有計策成功率 +25%。',
  'door-thief':   '關門捉賊 — 圍而不攻。包圍小股敵軍後，每回合敵 −10% 兵，逼降。',
  'tree-flower':  '樹上開花 — 借勢嚇敵。借盟軍旗號威懾，敵方士氣 −20%。',
  'guest-host':   '反客為主 — 漸進蠶食。在敵境內駐留 3 回合後，反過來掌控當地。',
  'feign-mad':    '假癡不癲 — 大智若愚。假裝平庸無能，使敵放鬆警惕，反擊時 War +20。',
  'pull-ladder':  '上屋抽梯 — 斷其退路。誘敵深入後切斷退路，敵全軍每回合 −15% 士氣。',
  // ── Phase 57: remaining 36-stratagems + 三國奇計 ──
  'borrow-knife': '借刀殺人 — 借敵勢力之手除敵。挑撥兩個敵國交戰，本方坐收漁利。',
  'lead-sheep':   '順手牽羊 — 乘隙取小利。途經敵境時，每回合自動奪取 5% 敵方糧草 / 兵力。',
  'borrow-corpse':'借屍還魂 — 借舊有威名復興。已亡勢力之名號可被借用，當前勢力獲 +20 民望。',
  'plum-peach':   '李代桃僵 — 棄車保帥。犧牲一員副將，主將與精銳兵力完整保全。',
  'borrow-road':  '假途伐虢 — 借道而行，順手取之。借盟友通道行軍，途中可奇襲沿途城池。',
  'switch-beam':  '偷梁換柱 — 暗中替換敵核心。摻入間諜替換敵主將參謀，敵計策全數失敗。',
  'point-curse':  '指桑罵槐 — 殺雞儆猴。處死某低階副將以儆全軍，己方所有將領 +15 忠誠。',
  'plum-thirst':  '望梅止渴 — 曹操故事。激勵口渴疲憊之兵，全軍士氣 +25%，持續 2 回合。',
  'seven-lamp':   '七星燈 — 諸葛延壽之術。年邁主將每回合恢復 1 點壽元，但失敗則立即死亡。',
  'chu-songs':    '四面楚歌 — 韓信絕招。包圍敵軍後唱其家鄉之歌，敵每回合 30% 機率部分倒戈。',
  'burn-bowang':  '火燒博望 — 諸葛初出茅廬之計。森林地形 + 風天可觸發，敵軍全軍 burning 3 回合。',
  'wooden-ox':    '木牛流馬 — 諸葛運糧器械。山地行軍時，每回合糧食消耗 −50%，可長期遠征。',
  // ── Phase 58: 三國名場面 + 孫子兵法 ──
  'hair-head':    '割髮代首 — 曹操踐麥律自罰之計。主將觸犯軍法時可選此代死，全軍忠誠 +20 + 軍紀 +30%。',
  'white-robe':   '白衣渡江 — 呂蒙取荊州之計。喬裝商隊渡江，敵守軍 100% 措手不及，奪城損失 −80%。',
  'song-map':     '張松獻圖 — 內應獻地圖之術。揭示敵境內所有城防 / 駐軍 / 糧草虛實，持續 3 回合。',
  'seven-grab':   '七擒孟獲 — 諸葛南征攻心之計。對異族 / 叛軍使用，每擒一次降伏 +25%，七次後永久歸順。',
  'tongue-war':   '舌戰群儒 — 諸葛說服東吳之術。主將魅力 / 智力 ≥85 時，可使中立勢力參戰己方。',
  changban:       '長坂單騎 — 趙雲救主之勇。兵力 <10% 時，主將自動突圍救出友軍，0 損失脫戰。',
  'zhuge-bow':    '諸葛連弩 — 連發十矢之弩。弓兵每回合多攻 2 次，但 −30% 移動。',
  'chain-ship':   '連環船 — 龐統獻策。水軍鎖船結陣，+40% 水戰穩定性，但若被火攻則全軍覆沒。',
  'burn-yiling':  '火燒連營 — 陸遜破劉備之計。敵軍連營七百里時觸發，全軍 burning + 大規模潰敗。',
  'know-self':    '知己知彼 — 孫子曰：百戰不殆。揭示敵主將屬性 / 計策 / 兵種克制，本戰全局加成 +15%。',
  'fast-strike':  '兵貴神速 — 孫子兵法。下回合本方所有單位行動點 +1，先機制敵。',
  deception:      '兵不厭詐 — 孫子曰：兵者，詭道也。計策成功率 +20%，但失敗時敵方識破回敬反傷。',
  // ── Phase 59 ──
  'attack-plans':   '上兵伐謀 — 孫子曰：上兵伐謀，其次伐交，其次伐兵。識破敵主帥意圖時，本方計策必中。',
  'attack-heart':   '攻心為上 — 孫子之術。敵將忠誠 <60 時，本方說降成功率 +50%。',
  'surround-three': '圍三闕一 — 孫子兵法。圍城時故意留一缺口，敵軍因逃路而潰散，攻城傷亡 −40%。',
  'subdue-no-fight':'不戰而屈人之兵 — 孫子最高境界。本方軍力顯著優勢時，敵小城自動投降。',
  'hide-light':     '韜光養晦 — 六韜之術。本方隱藏實力，敵方情報失準，計策對我方失效。',
  'total-victory':  '全勝之道 — 孫子曰：全國為上，破國次之。完整奪城（不破壞）獲 +30% 民忠。',
  'water-form':     '兵形象水 — 孫子曰：兵無常勢。本方陣形每回合可自由切換，無延遲。',
  'ortho-extra':    '以正合奇勝 — 孫子曰：凡戰者，以正合，以奇勝。正面拉鋸 + 奇兵突襲，敵防 −25%。',
  'qimen-dunjia':   '奇門遁甲 — 道家排兵之法。本方部隊在地圖上隱形 1 回合，敵無法定位攻擊。',
  'star-prayer':    '諸葛禳星 — 諸葛延壽古術。年邁主將生命 +5 年（每場戰役限一次，失敗則立死）。',
  'he-luo-tu':      '河圖洛書 — 上古先天八卦。揭示天象 / 異象的全部影響，未來 3 回合占卜結果可見。',
  'five-thunder':   '五雷正法 — 道家斬妖術。直接擊殺敵方計謀型將領（INT >80），但要求己方道術士在場。',
  'sneak-yinping':  '偷渡陰平 — 鄧艾滅蜀奇兵。穿越無路之山，從後方繞至敵都，無視所有沿途守軍。',
  'nine-campaigns': '九伐中原 — 姜維北伐意志。本主將無論勝敗，士氣不下 50，可連續發動 9 次戰役。',
  'xiling-stand':   '西陵之戰 — 陸抗對抗晉軍。被多面圍攻時 +50% 守城戰力，可堅守 5 倍時間。',
  'feign-illness':  '裝病奪權 — 司馬懿閉門裝病之計。本方主將被視為失能，敵放鬆警惕後突然反擊 +60%。',
  'iron-chain':     '鐵索橫江 — 王濬破吳前奏。鐵索鎖江阻敵舟船，水路全封，3 回合內敵無法水路機動。',
  'two-tigers':     '二虎競食 — 曹操驅劉備之計。挑撥兩員猛將互鬥，至少一方陣亡。',
  'lure-tiger-wolf':'驅虎吞狼 — 曹操之術。挑唆敵國攻打另一敵國，本方 2 回合內無人來犯。',
  'sow-discord-2':  '離間挑撥 — 散布謠言離間敵君臣。敵主將與其副將忠誠各 −15。',
  'thousand-ride':  '千里走單騎 — 關羽護嫂之程。被俘武將自動逃出，且可帶走最多 2 員嫂屬。',
  'lone-blade':     '單刀赴會 — 關羽魯肅鴻門宴。單將赴敵宴可成功談判，或硬殺對方主將。',
  'pass-six':       '過五關斬六將 — 關羽歸劉之路。連續突破 6 個敵境，每關擊殺一名守將。',
  'burn-xinye':     '火燒新野 — 諸葛二度火攻。城將陷時主動焚城，敵方接收城池 −80% 資源。',
  'solid-camp':     '結硬寨打呆仗 — 曾國藩湘軍之法。圍城每回合穩步進兵 5%，3 個月內必下任何城。',
  'death-ground':   '置之死地而後生 — 孫子之術。本方兵 <20% 時，自動觸發 +40% 攻擊 + +30% 防御。',
  'siege-relief':   '圍點打援 — 圍城打援。圍住一城吸引敵救援，本方主力埋伏中途，伏擊援軍。',
  bloodless:        '兵不血刃 — 不戰而勝。對方城池民忠 <30 + 駐軍 <10% 時可直接接收，無損失。',
  // ── Phase 60 ──
  'plan-war':       '計戰 — 百戰奇法首篇。戰前完整偵察 + 演練，所有計策成功率 +25%。',
  'cavalry-war':    '騎戰 — 騎兵突擊之要。平原作戰時騎兵 +30% 衝擊力，可貫穿至後排。',
  'naval-war':      '舟戰 — 水軍指揮。江河湖海戰時主將生效，水軍戰力 +40%，登陸傷亡 −30%。',
  'trust-war':      '信戰 — 賞信罰必。本主將忠誠 ≥90 時可使全軍士氣 +20，敵離間計失效。',
  'many-war':       '眾戰 — 以多勝寡之法。兵力 >敵 1.5 倍時，攻擊 +15%，戰場效率 +25%。',
  'few-war':        '寡戰 — 以少勝多之術。兵力 <敵 50% 時，主將指揮加成 +50%，士氣不墜。',
  'mountain-war':   '山戰 — 險地用兵。山地 / 關隘地形時，防御 +50%，可設伏。',
  'night-war':      '夜戰 — 月黑風高夜襲營。夜間發動奇襲，敵軍恐慌，行動點 −1。',
  'supply-war':     '糧戰 — 兵馬未動，糧草先行。糧道暢通時持久戰能力 +100%。',
  'defend-war':     '守戰 — 堅壁清野守城法。守城傷亡 −40%，可堅守至援軍到達。',
  'fire-ox':        '火牛陣 — 田單破燕之法。牛尾繫火，奔入敵陣，破甲陣 + 燒輜重。',
  'sand-dam':       '韓信囊沙 — 濰水之戰絕計。築沙袋阻河，伏兵半渡而擊。',
  'ban-chao':       '班超三十六 — 投筆從戎之勇。36 人可擒敵國使團，外交斬首奇襲。',
  'mass-burial':    '白起坑卒 — 長平四十萬。俘虜全部坑殺，敵國恐懼士氣 −30%，但 −50 民望。',
  'long-ride':      '霍去病千里 — 漠北遠征。騎兵可長驅 6 城距離不補給，奇襲敵後方。',
  surprise:         '出其不意 — 孫子心法。攻其未防之地，敵守軍 −60% 防御。',
  unguarded:        '攻其無備 — 趁敵不備。敵在內政 / 移動時發起攻擊，傷害 +35%。',
  'wind-forest':    '風林火山 — 速、靜、烈、不動之四象。本主將每回合切換一態，全軍 +15% 適應力。',
  'quick-decision': '速戰速決 — 孫子曰：兵聞拙速。3 回合內結束戰鬥則民忠 +20，否則 −10。',
  protracted:       '持久戰 — 耐力之爭。本方守備時，敵每回合士氣 −5，糧消 +20%。',
  'warm-wine':      '溫酒斬華雄 — 關羽神勇之始。對 War >85 的敵將，30% 機率瞬殺。',
  'three-fight-lubu':'三英戰呂布 — 劉關張合戰。三員結義武將同陣時，可對抗任何單將。',
  'plum-wine':      '煮酒論英雄 — 曹操試劉備之術。揭示敵主將真實意圖 + 性格全部。',
  longzhong:        '隆中對 — 三分天下之策。本方擁有 3+ 個州時，外交 / 內政全 +20%。',
  'burn-chibi':     '火燒赤壁 — 周郎妙計。連環船 + 東風 + 火攻三組合時觸發，敵水軍全滅。',
  'lose-jingzhou':  '大意失荊州 — 關羽教訓。對方輕敵 (War >90 + INT <60) 時，可奇襲奪城。',
  'flee-maicheng':  '走麥城 — 末路逃亡。主將兵 <5% 時自動撤退，但忠誠 −20。',
  'white-emperor':  '白帝託孤 — 劉備傳位之術。主將臨終可指定繼承人 +50 忠誠，無權力鬥爭。',
  'tearful-ma':     '揮淚斬馬謖 — 諸葛執法。處決一員無能副將，全軍 +30 紀律，但 −5 民忠。',
  'wuzhang-star':   '五丈原星隕 — 諸葛殞落。主將陣亡時，落星象徵全軍 −50 士氣，可能潰散。',
  memorial:         '出師表 — 鞠躬盡瘁。發表後本主將忠誠 +30，全軍士氣 +25，但壽元 −2 年。',
  'edict-belt':     '衣帶詔 — 漢獻帝密旨。煽動敵國臣下叛變，敵主將忠誠 −10 + 1 員可能倒戈。',
  'borrow-jingzhou':'借荊州 — 劉備借而不還。和敵盟友協議借取領土，3 年後敵憤怒索要。',
  diaochan:         '貂蟬連環 — 美人離間。對父子 / 主從關係的兩位敵將，使其反目。',
  'liu-bei-share-meat':'推食食人 — 劉備愛兵之術。每回合主將分糧予兵，全軍忠誠 +5。',
  'no-clash':       '兵不接刃 — 不戰勝。對方士氣 <20 時自動投降。',
  'mind-might':     '將謀重於兵勇 — 智勝勇。本方主將 INT >敵主將 20 點時，戰力差不受兵力影響。',
  'reverse-encircle':'反包圍 — 假被圍實圍人。佯裝被困誘敵深入後反包圍，傷害 +50%。',
  'flower-bloom':   '中心開花 — 兵分四路圍。主力突入敵中央後四面開花，全方位攻擊。',
  annihilate:       '殲滅戰 — 不留活口。戰勝後敵軍全滅，不留俘虜，本方士氣 +20，民忠 −10。',
  attrition:        '消耗戰 — 拼國力。長期對峙，本國庫存 >敵時，每回合敵 −5% 兵。',
  'scorched-earth': '焦土戰術 — 退而焚之。撤退時焚毀城池，敵接收 −80% 資源 + −50% 民忠。',
  'siege-starve':   '圍困飢戰 — 困而餓之。圍城每回合敵 −10% 糧，糧盡時不戰自降。',
  'break-encircle': '突圍戰 — 死戰殺出。被圍時所有兵力集中突破一點，傷亡 −30%。',
  'bait-trap':      '釣餌戰術 — 引魚上鉤。故意暴露弱點誘敵深入，觸發埋伏 + 反擊 +60%。',
  'encircle-no-attack':'圍而不攻 — 兵法之上。圍而不打，待敵自亂 / 議降，無傷亡接收。',
  'heart-war':      '心戰為上 — 攻心為上之延伸。每回合敵軍可能因恐懼 / 飢餓 / 思鄉投降。',
  'counter-plot':   '將計就計 — 反向破敵。本主將 INT >敵 INT 15 點時，敵計策全部回敬反噬。',
  'press-pursuit':  '趁勢追擊 — 痛打落水狗。敵兵 <30% 時主動追擊，敵 100% 全滅。',
  'still-vs-motion':'以靜制動 — 後發制人。守備位置一回合不動，下回合所有反擊 +50%。',
  // ── Phase 61 ──
  'plan-state':       '圖國 — 吳子首篇。內政 +20% / 軍備 +15%。先治國再用兵。',
  'assess-enemy':     '料敵 — 吳起察敵之術。揭示敵 6 弱點：糧 / 兵 / 將 / 城 / 路 / 卒。',
  'govern-troops':    '治兵 — 吳子治軍之道。每回合士氣 +10，逃兵 −80%。',
  'on-generalship':   '論將 — 吳子論武將標準。主將屬性各項提升 +5。',
  'adapt-change':     '應變 — 吳子應變之術。戰場上每回合可重選陣型，無冷卻。',
  'inspire-soldiers': '勵士 — 吳子激勵之術。賞罰分明，全軍 +25% 攻擊力 1 回合。',
  'benevolence-root': '仁本 — 司馬法之首。仁愛為本，民忠 +15，敵軍士氣 −5。',
  'emperor-duty':     '天子之義 — 司馬法。代天征伐，敵國敵意 +20，但本軍正義性 +30%。',
  'set-ranks':        '定爵 — 司馬法之術。軍中爵位明確，將領忠誠 +10，指揮 +10%。',
  'strict-position':  '嚴位 — 司馬法。軍規嚴明，逃兵 0，但忠誠 −5。',
  'use-many':         '用眾 — 司馬法。10 萬以上大軍效率 +20%，後勤承載 +30%。',
  'five-virtues':     '將之五善 — 諸葛論將五德：仁 / 義 / 禮 / 智 / 信。主將齊備時所有指揮 +30%。',
  'authority-war':    '兵權 — 諸葛兵權。主將絕對指揮，副將不可違令，但個人能力 +0。',
  'know-nature':      '知人性 — 諸葛知人之術。揭示己方所有武將真實忠誠 / 性格 / 隱密。',
  'when-not-fight':   '不戰之機 — 諸葛兵法。識別不可戰之時，自動規避必敗戰役。',
  'observe-general':  '觀將 — 諸葛觀將法。揭示敵將意志 / 計策 / 心理弱點。',
  'eagle-strike':     '鷹擊長空 — 高處俯衝突襲。高地優勢時，襲擊 +35%。',
  'tiger-crouch':     '虎踞龍盤 — 險要據守。地形優越時，守軍 +50% 戰力。',
  'leopard-wolf':     '豹突狼奔 — 突擊小隊。少而精的快速突進，士兵 <2000 時 +30% 機動。',
  'crane-chickens':   '鶴立雞群 — 一人鎮萬軍。本主將 War >90 + 武將獨來時，敵眾將恐慌 −20% 攻。',
  'snake-rat':        '蛇行鼠竄 — 散兵游擊。全軍轉為小隊化，敵 AOE 攻擊 −60%。',
  'bee-swarm':        '蜂擁而上 — 人海戰術。同時多路突擊，每路傷亡分散 25%。',
  'ant-siege':        '蟻附攻城 — 雲梯雲集。攻城時兵力傷亡翻倍，但破城速度 ×3。',
  'whale-silk':       '鯨吞蠶食 — 漸進蠶食。本方每回合自動奪取敵 5% 邊境，無戰鬥。',
  'half-cross':       '半渡而擊 — 渡河奇襲。敵渡河途中發動攻擊，敵 −50% 戰力。',
  'array-wait':       '列陣以待 — 嚴陣以待。先布陣後待敵來，本方守勢 +30%。',
  'conserve-strength':'養精蓄銳 — 休整待機。一回合不戰，下次戰役全軍狀態恢復 100%。',
  'high-ground':      '居高臨下 — 山頂之利。山地戰時，所有計策成功率 +20%。',
  'mountain-back':    '背山臨水 — 進退兼具。山水陣型，被圍時 −50% 損失。',
  'intercept-relief': '截擊援軍 — 圍點打援之執行。可中途攔截敵援軍，使被圍敵孤立無援。',
  'rush-supply':      '急襲糧道 — 斷敵後勤。敵主力 3 回合內缺糧 −20% 戰力。',
  'feign-defeat':     '詐敗誘敵 — 假敗真伏。主動敗退引敵深入，觸發大規模反伏。',
  'set-ambush-path':  '設伏要道 — 兵家必爭之路。在敵必經路設伏，敵通過時 100% 重創。',
  'quick-night':      '速戰夜襲 — 月黑風高。夜戰時偷襲敵營，30% 機率俘虜敵主將。',
  'star-reading':     '占星望氣 — 觀天象識戰機。揭示下季所有異象，提前準備或迴避。',
  'tortoise-shell':   '卜筮龜甲 — 占卜決疑。本回合所有決策 +50% 成功率。',
  'elements-counter': '五行相剋 — 道家剋制論。兵種剋制下，戰力差距翻倍（金克木，水剋火…）。',
  talisman:           '護身符 — 道家法寶。主將免疫一次致命傷害，物品保留至下場戰役。',
  'summon-spirits':   '招神召將 — 道家神將術。可召喚一名已陣亡名將靈助戰 1 回合。',
  'julu-battle':      '鉅鹿之戰 — 項羽破釜沉舟。本軍兵力 1/3 而戰勝強敵，士氣 +50。',
  'muye-battle':      '牧野之戰 — 武王伐紂。對暴政敵國，敵內部 50% 倒戈。',
  'chengpu-battle':   '城濮之戰 — 晉文公退避三舍。先讓後勝，本方戰局態勢逆轉 +30%。',
  'hanzhong-battle':  '漢中之戰 — 劉備奪漢中。長期消耗後一舉破敵，戰役後民忠 +25。',
  'lose-jieting':     '街亭失守 — 馬謖之失。教訓全軍：副將自負 = 戰術失敗概率 +60%。',
  'zhao-yun-baby':    '趙雲懷主 — 長坂坡七進七出。本主將兵 <5% 時仍可帶走 1 員副將安全脫戰。',
  'huang-zhong-dingjun':'黃忠定軍山 — 老將斬夏侯淵。老年武將（>55 歲）攻擊 +30% / 致命一擊 +25%。',
  'zhou-yu-plan':     '周郎妙計 — 美人陷計。聯敵之兄弟 / 親家入局，敵陣營分裂。',
  'seek-talent':      '求賢令 — 曹操唯才是舉。本回合內全國招募成功率 +50%，無門第限制。',
  'he-jin-blunder':   '何進召董 — 引狼入室。誤召敵勢力，本國控制力崩潰。教訓：戒備引外援。',
};

const CATEGORIES: CatalogCategory[] = [
  { key: 'melee',    zh: '近戰', en: 'Melee',    color: '#b8442e' },
  { key: 'ranged',   zh: '遠程', en: 'Ranged',   color: '#b8c87a' },
  { key: 'mystic',   zh: '奇門', en: 'Mystic',   color: '#c178c7' },
  { key: 'disrupt',  zh: '擾亂', en: 'Disrupt',  color: '#88b7e8' },
  { key: 'strategy', zh: '策略', en: 'Strategy', color: '#d4a84a' },
];

interface Props { onClose: () => void; }

export function TacticsModal({ onClose }: Props) {
  const items: CatalogItem[] = Object.entries(TACTIC_DEFS).map(([id, def]) => ({
    id,
    zh: def.zh,
    en: def.en,
    description: TACTIC_DESC[id] ?? '',
    category: TACTIC_CATEGORY[id] ?? 'melee',
  }));
  return (
    <CatalogModal
      onClose={onClose}
      title={{ zh: '戰法', en: 'Tactics' }}
      items={items}
      categories={CATEGORIES}
    />
  );
}
